bump_version: null
lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
nf_core_version: 3.0.1
org_path: null
repository_type: pipeline
template:
  author: Jonas Scheid, Steffen Lemke, Leon Bichmann, Marissa Dubbelaar
  description: Identify and quantify peptides from mass spectrometry raw data
  force: false
  is_nfcore: true
  name: mhcquant
  org: nf-core
  outdir: .
  skip_features: null
  version: 2.6.1dev
update: null
